# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'monitoring/grafana'
    static_configs:
    - targets: ['grafana:3000']
  - job_name: 'monitoring/prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'monitoring/loki'
    static_configs:
    - targets: ['loki:3100']
  - job_name: 'monitoring/tempo'
    static_configs:
    - targets: ['tempo:80']
  # - job_name: 'tns/app'
  #   static_configs:
  #   - targets: ['app:80']
  # - job_name: 'tns/db'
  #   static_configs:
  #   - targets: ['db:80']
  # - job_name: 'tns/loadgen'
  #   static_configs:
  #   - targets: ['loadgen:80']
  - job_name: 'monitoring/docker'
    static_configs:
    - targets: ['docker.for.mac.host.internal:9323']
  - job_name: 'monitoring/node_exporter'
    static_configs:
    - targets: ['node_exporter:9100']
  - job_name: 'monitoring/cadvisor'
    static_configs:
    - targets: ['cadvisor:8080']
  - job_name: "docker-containers"
    docker_sd_configs:
      - host: unix:///var/run/docker.sock # You can also use http/https to connect to the Docker daemon.
    relabel_configs:
      # Only keep containers that have a `prometheus-job` label.
      - source_labels: [__meta_docker_container_label_prometheus_job]
        regex: .+
        action: keep
      # Use the task labels that are prefixed by `prometheus-`.
      - regex: __meta_docker_container_label_prometheus_(.+)
        action: labelmap
        replacement: $1
